# Generated by Django 5.2.7 on 2025-11-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCat', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMarca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(default=0)),
                ('combustible', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('idCat', models.ManyToManyField(to='appOutletCar.categoria')),
                ('idMarca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.marca')),
            ],
        ),
    ]
