# Generated by Django 5.2.7 on 2025-11-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='km',
            field=models.IntegerField(default=0),
        ),
    ]
