# Generated by Django 5.2.7 on 2025-11-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0002_coche_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCombustible', models.CharField(max_length=50)),
            ],
        ),
    ]
