# Generated by Django 5.2.7 on 2025-11-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0003_combustible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='combustible',
        ),
        migrations.AddField(
            model_name='coche',
            name='combustible',
            field=models.ManyToManyField(to='appOutletCar.combustible'),
        ),
    ]
