# Generated by Django 5.2.7 on 2025-11-08 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0004_remove_coche_combustible_coche_combustible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='coche',
            name='combustible',
        ),
        migrations.RemoveField(
            model_name='coche',
            name='precio',
        ),
        migrations.AddField(
            model_name='coche',
            name='idCombustible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.combustible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coche',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coche',
            name='km',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='coche',
            name='idPrecio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appOutletCar.oferta'),
        ),
    ]
