# Generated by Django 5.2.7 on 2025-11-13 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0005_oferta_remove_coche_combustible_remove_coche_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='idCat',
            field=models.ManyToManyField(related_name='categoria', to='appOutletCar.categoria'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='idCombustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combustible', to='appOutletCar.combustible'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='idMarca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marca', to='appOutletCar.marca'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='idPrecio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta', to='appOutletCar.oferta'),
        ),
    ]
