# Generated by Django 5.2.7 on 2025-11-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0006_alter_coche_idcat_alter_coche_idcombustible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_coches/'),
        ),
    ]
