# Generated by Django 5.2.7 on 2025-12-07 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0007_coche_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='idPrecio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta', to='appOutletCar.oferta'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='km',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coche',
            name='matricula',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.coche')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'coche')},
            },
        ),
    ]
