# Generated by Django 5.2.7 on 2025-12-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0008_alter_coche_idprecio_alter_coche_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='idPrecio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta', to='appOutletCar.oferta'),
        ),
    ]
